### PR TITLE
implement add_undirected_edges

### PR DESCRIPTION
**Pull request by laifi**
Implementing the add_undirected_edges to makes all edges of the given graph bi-directional.

### CODE REVIEW

**Comment by laifi** [comment]
@googlebot I signed it!

**Comment by aheydon-google** [comment]
Hi, @laifi, thanks for the PR.

I'm a bit confused by this change, as the `add_undirected_edges()` function is already implemented (see [here](https://github.com/tensorflow/neural-structured-learning/blob/master/neural_structured_learning/tools/graph_utils.py#L98-L103)). You can also see a unit test of the function demonstrating that it works [here](https://github.com/tensorflow/neural-structured-learning/blob/master/neural_structured_learning/tools/graph_utils_test.py#L40-L57)).

Is there something about the current implementation you find lacking or that you were trying to fix?

Thanks,

Allan

**Comment by laifi** [comment]
@aheydon-google Sorry , I was going through the code source and I found this function I got confused with the inner function [all_graph_edges( ) ](https://github.com/tensorflow/neural-structured-learning/blob/c1fc41808e43784b971779cfeafa213807e708df/neural_structured_learning/tools/graph_utils.py#L91) so I thought the undirected graphs still not supported but it seems good with the current implementation.
Actually, I'm really interested in this framework and I would like to be part of it , If you have already defined roadmap or some functionalities still not implemented I could help.
You can close this PR , Thanks :)

**Comment by aheydon-google** [comment]
Okay, thanks for getting back to me! - Allan

**Pull request closed without merging**
